<!-- News Detail Article -->
<div class="container mt-5 pt-4 mb-5 pb-5">
    <div class="row justify-content-center">
        <div class="col-lg-8" data-aos="fade-up">
            <!-- Article Header -->
            <div class="mb-5 text-center">
                <?php if ($article['category_name']): ?>
                    <a href="?action=news&category=<?= htmlspecialchars($article['category_name']) ?>" class="badge bg-primary px-3 py-2 rounded-pill fs-6 mb-3 text-decoration-none">
                        <?= htmlspecialchars($article['category_name']) ?>
                    </a>
                <?php endif; ?>
                
                <h1 class="fw-bold mb-4 display-4" style="letter-spacing: -1px; line-height: 1.2;">
                    <?= htmlspecialchars($article['title']) ?>
                </h1>
                
                <div class="d-flex align-items-center justify-content-center flex-wrap gap-4 text-muted mb-4">
                    <span><i class="bi bi-calendar3 me-1"></i> <?= date('d/m/Y', strtotime($article['created_at'])) ?></span>
                    <span><i class="bi bi-eye me-1"></i> <?= number_format($article['views']) ?> lượt xem</span>
                    <span><i class="bi bi-share me-1"></i> Chia sẻ</span>
                </div>

                <?php if ($article['summary']): ?>
                    <p class="fs-4 text-secondary mb-0 fw-medium" style="line-height: 1.6;">
                        <?= htmlspecialchars($article['summary']) ?>
                    </p>
                <?php endif; ?>
            </div>
            
            <!-- Featured Image -->
            <?php if ($article['image_url']): ?>
                <div class="mb-5 rounded-4 overflow-hidden shadow-lg">
                    <img src="<?= htmlspecialchars($article['image_url']) ?>" class="w-100 img-fluid" alt="<?= htmlspecialchars($article['title']) ?>">
                </div>
            <?php endif; ?>

            <!-- Article Content -->
            <div class="news-content fs-5" style="line-height: 1.8; color: #333;">
                <?= $article['content'] // Content is HTML generated by QuillJS, DO NOT htmlspecialchars ?>
            </div>
            
            <!-- Author & Share -->
            <div class="d-flex justify-content-between align-items-center mt-5 pt-4 border-top">
                <div class="d-flex align-items-center gap-3">
                    <div class="bg-light rounded-circle d-flex align-items-center justify-content-center text-primary fw-bold" style="width: 50px; height: 50px; font-size: 1.2rem;">
                        GT
                    </div>
                    <div>
                        <div class="fw-bold mb-0">Ban Biên Tập Gentech</div>
                        <small class="text-muted">Đăng lúc <?= date('H:i', strtotime($article['created_at'])) ?></small>
                    </div>
                </div>
                <div class="d-flex gap-2">
                    <button class="btn btn-outline-secondary rounded-circle" style="width: 40px; height: 40px;"><i class="bi bi-facebook"></i></button>
                    <button class="btn btn-outline-secondary rounded-circle" style="width: 40px; height: 40px;"><i class="bi bi-twitter-x"></i></button>
                    <button class="btn btn-outline-secondary rounded-circle" style="width: 40px; height: 40px;"><i class="bi bi-link-45deg"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
/* Styling for QuillJS content rendering inside the site */
.news-content img {
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    margin: 1.5rem 0;
}
.news-content h2, .news-content h3 {
    font-weight: 700;
    margin-top: 2rem;
    margin-bottom: 1rem;
    letter-spacing: -0.5px;
}
.news-content blockquote {
    border-left: 4px solid #0d6efd;
    padding-left: 1.5rem;
    margin: 2rem 0;
    font-style: italic;
    color: #555;
    background: #f8fafc;
    padding: 1.5rem;
    border-radius: 0 8px 8px 0;
}
.news-content a {
    color: #0d6efd;
    text-decoration: none;
    font-weight: 500;
}
.news-content a:hover {
    text-decoration: underline;
}
</style>
