<?php

$action = $_GET['action'] ?? '/';


match ($action) {
    '/' => (new HomeController)->index(),
    'about' => (new HomeController)->about(),
    'news'  => (new HomeController)->news(),
    'support' => (new HomeController)->support(),
    'products' => (new HomeController)->products(),
    'product-detail' => (new HomeController)->productDetail(),
    'cart' => (new HomeController)->cart(),
    'checkout' => (new HomeController)->checkout(),

    'login'         => (new AuthController)->login(),
    'post-login'    => (new AuthController)->postLogin(),
    'register'      => (new AuthController)->register(),
    'post-register' => (new AuthController)->postRegister(),
    'logout'        => (new AuthController)->logout(),

    'admin'                 => (new AdminController)->dashboard(),
    'admin-categories'      => (new AdminController)->categories(),
    'admin-category-form'   => (new AdminController)->categoryForm(),
    'admin-category-detail' => (new AdminController)->categoryDetail(),
    'admin-category-create' => (new AdminController)->categoryCreate(),
    'admin-category-update' => (new AdminController)->categoryUpdate(),
    'admin-category-delete' => (new AdminController)->categoryDelete(),
    'admin-brands'          => (new AdminController)->brands(),
    'admin-brand-form'      => (new AdminController)->brandForm(),
    'admin-brand-detail'    => (new AdminController)->brandDetail(),
    'admin-brand-create'    => (new AdminController)->brandCreate(),
    'admin-brand-update'    => (new AdminController)->brandUpdate(),
    'admin-brand-delete'    => (new AdminController)->brandDelete(),
    'admin-products'        => (new AdminController)->products(),
    'admin-product-create'  => (new AdminController)->createProduct(),
    'admin-product-edit'    => (new AdminController)->editProduct(),
    'admin-product-delete'  => (new AdminController)->deleteProduct(),
    'admin-users'           => (new AdminController)->users(),
    'admin-user-create'     => (new AdminController)->createUser(),
    'admin-user-store'      => (new AdminController)->storeUser(),
    'admin-user-edit'       => (new AdminController)->editUser(),
    'admin-user-update'     => (new AdminController)->updateUser(),
    'admin-user-delete'     => (new AdminController)->deleteUser(),
    'admin-user-status'     => (new AdminController)->changeUserStatus(),
    'admin-orders'          => (new AdminController)->orders(),
    'admin-order-detail'    => (new AdminController)->orderDetail(),
    'admin-profile'         => (new AdminController)->profile(),
    'admin-update-profile'  => (new AdminController)->updateProfile(),
    'admin-change-password' => (new AdminController)->changePassword(),
    'admin-update-password' => (new AdminController)->updatePassword(),
};
